### PR TITLE
[For questions only] Initial attempt to upgrade to 2022.1.1-beta-4

### PR DESCRIPTION
**Pull request by agelsomini**
@virtuald I ran into issues attempting to fix the first error I ran into :( I figure I'm missing something obvious that you might be able to quickly answer.

I rebuilt wpiutil (https://github.com/agelsomini/robotpy-wpiutil/tree/feature/upgrade-to-2022.1.1-beta-4).  I know its not complete, from my earlier investigation I know that there should be work around changes from wpi::ArrayRef to wpi::span at a minimum but a quick rebuild let me move on to wpimath.

I'm running into the following error in ExtendedKalmanFilter.h.  Looking at the diff between the tags for 2021.3.1 and 2022.1.1-beta-4 it only looked to be parameter type changes (mostly switches from Eigen::Matrix to Eigen::Vector).  If you can point me in the right direction that would help.

```
(venv) ➜ luxo-linux:robotpy-rebuild/build/robotpy-wpimath git:(feature/upgrade-to-2022.1.1-beta-4) ✗ python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_gen
running build_dl
Traceback (most recent call last):
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/hooks.py", line 751, in class_hook
    self._function_hook(fn, method_data, internal=internal)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/hooks.py", line 488, in _function_hook
    raise ValueError(
ValueError: Correct: must specify template impls for function template

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 32, in call_hook
    hook(*args)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/hooks.py", line 753, in class_hook
    raise HookError(f"{cls_key}::{fn['name']}") from e
robotpy_build.hooks.HookError: ExtendedKalmanFilter::Correct

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/wrapper.py", line 674, in on_build_gen
    processor.process_config(cfg, data, hooks)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 141, in process_config
    return self._process_config(cfg, data, hookobj)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 182, in _process_config
    data = process_module(cfg, hooks, gbls)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 110, in process_module
    headers = [process_header(cfg, header, hooks, data) for header in cfg.headers]
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 110, in <listcomp>
    headers = [process_header(cfg, header, hooks, data) for header in cfg.headers]
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 100, in process_header
    _process_class(cls, hooks, data)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 43, in _process_class
    call_hook(cls["name"], hooks, 'class_hook', cls, data)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/header2whatever/parse.py", line 34, in call_hook
    raise HookError(hook_name + ": " + name) from e
header2whatever.parse.HookError: class_hook: ExtendedKalmanFilter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alg/frc/robotpy-rebuild/build/robotpy-wpimath/setup.py", line 5, in <module>
    setup()
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/setup.py", line 197, in setup
    s.run()
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/setup.py", line 191, in run
    _setup(**self.setup_kwargs)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/command/build_py.py", line 16, in run
    self.run_command("build_gen")
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/command/build_gen.py", line 36, in run
    wrapper.on_build_gen(self.cxx_gen_dir)
  File "/home/alg/frc/robotpy-rebuild/build/venv/lib/python3.9/site-packages/robotpy_build/wrapper.py", line 676, in on_build_gen
    raise ValueError(f"processing {header}") from e
ValueError: processing frc/estimator/ExtendedKalmanFilter.h
(venv) ➜ luxo-linux:robotpy-rebuild/build/robotpy-wpimath git:(feature/upgrade-to-2022.1.1-beta-4) ✗ 
```

### CODE REVIEW

**Comment by virtuald** [comment]
Template parameters cannot be autodetected at this time. See https://robotpy-build.readthedocs.io/en/latest/autowrap.html#class-templates for documentation on how to properly specify templates.

**Comment by virtuald** [comment]
Actually, that error is about a function template, so see the section below that (it's basically the same issue).

**Comment by agelsomini** [comment]
Thanks I'll take a look at that.  I think my initial thought was there is nothing net new here, there are no new overloads, the function template is still based on the number of rows.  The only changes were the parameters so I assumed that making those changes would be enough, but i'll spend some time with the docs so I understand what is going on in there better.

**Comment by virtuald** [comment]
Unfortunately template support is a bit ugly right now. I'm guessing that the parameters don't match what it's looking for, or there's an additional overload that isn't accounted for.

**Comment by agelsomini** [comment]
Could the issue be that we need to explicitly add Eigen::Vector to here?
https://github.com/robotpy/robotpy-build/blob/975b60dfd3ef405757d41104c3da99f4f1db978a/robotpy_build/pkgcfg.py#L37

This is supposed to be an ignored overload that its obviously not matching.  I'm looking through hooks.py to try and figure out why its not matching the overload

**Comment by auscompgeek** [comment]
> Could the issue be that we need to explicitly add Eigen::Vector to here?

That'd probably help - I can see `ExtendedKalmanFilter::SetXhat` has an `Eigen::Vector` overload.

> This is supposed to be an ignored overload that its obviously not matching. I'm looking through hooks.py to try and figure out why its not matching the overload

It might be hard to notice, but such a scenario robotpy-build will output a warning at build_gen time that an overload is missing from the YAML. Running `robotpy-build create-gen` will spit out the same output.

**Comment by agelsomini** [comment]
> It might be hard to notice, but such a scenario robotpy-build will output a warning at build_gen time that an overload is missing from the YAML. Running `robotpy-build create-gen` will spit out the same output.

Oh that is useful.  It also verifies that I'm able to match other uses of Eigen::Vector so I can clean up the remaining cases and then figure out what is wrong with ExtendedKalmanFilter

**Comment by agelsomini** [comment]
@auscompgeek Thanks that helped, must have had a typo in there somewhere.  Copying the one over from create-gen got me past that point.

**Comment by virtuald** [comment]
Closed in favor of #23

**Pull request closed without merging**
